%YAML:1.0

#common parameters 
#
# TODO: change these topics 
imu_topic: "/imu0"
image_topic: "/cam0/color" # "/cam0/image_raw"
output_path: "vins_result.csv"         # vins outputs will be wrttento vins_folder_path + output_path

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 512
image_height: 512
distortion_parameters:
   k1: 0.
   k2: 0.
   p1: 0.
   p2: 0.
projection_parameters: 
  #  615.426, 625.456, 318.837, 240.594
   fx: 615.426
   fy: 625.456
   cx: 318.837
   cy: 240.594

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1 #1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning. 
ex_calib_result_path: "ex_calib_result.yaml"  # If you choose 1 or 2, the extrinsic calibration result will be written vins_folder_path + ex_calib_result_path.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [-0.99953071, 0.00744168, -0.02971511, 
           0.0294408, -0.3459565, -0.99896766, 
           -0.00846201, -0.99937369, 0.03436032]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   # data: [-0.02,-0.06, 0.01]
   data: [0.04536566, -0.071996, -0.04478181]

#feature traker paprameters
max_cnt: 150  # 150          # max feature number in feature tracking
min_dist: 30  # 30          # min distance between two features 
freq: 10 # 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 3.0 # 2.0 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # 1 if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.1  # 0.04 max solver itration time (ms), to guarantee real time
max_num_iterations: 15   # 8 max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
# TODO: figure out these parameters
acc_n: 0.07           # accelerometer measurement noise standard deviation. #0.001372
gyr_n: 0.004          # gyroscope measurement noise standard deviation.
acc_w: 0.00172 # 0.000277          # accelerometer bias random work noise standard deviation. 
gyr_w: 0.000044 # 0.00003428        # gyroscope bias random work noise standard deviation.     #0.000003428
g_norm: 9.80766     # gravity magnitude


#loop closure parameters
loop_closure: 0 # 1   #if you want to use loop closure to minimize the drift, set loop_closure true and give your brief pattern file path and vocabulary file path accordingly;
                     #also give the camera calibration file same as feature_tracker node
pattern_file: "/support_files/brief_pattern.yml"
voc_file: "/support_files/brief_k10L6.bin"
min_loop_num: 25


